// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    if (consentChoice()) this.setState({ cookieDone: true });
    let reduce = false;
    try { reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}
    if (reduce) { this.setState({ reduced: true }); return; }
  }
  componentWillUnmount() { if (this._timer) clearInterval(this._timer); if (this._io) this._io.disconnect(); }
  renderVals() {
    const tick = (this.state && this.state.tick) || 0;
    const reduced = !!(this.state && this.state.reduced);
    return {
      apFeed: (() => {
        const steps = [
          'Campaign drafted from your product page',
          'Brief and deliverables written',
          'Sourced 48 creators who fit your brand',
          'Top 12 matched by audience and engagement',
          'Invites sent with your offer',
          'Shipping arranged for approved creators',
          'Follow ups sent to keep content on time'
        ];
        const phase = reduced ? steps.length : tick % (steps.length + 3);
        const count = Math.min(phase + 1, steps.length);
        const allDone = phase >= steps.length;
        const items = steps.slice(0, count).map((t, i) => {
          const run = !allDone && i === count - 1;
          return { text: t, run: run, done: !run, icBg: run ? 'transparent' : '#FFFFFF', when: run ? 'Now' : (count - 1 - i === 0 ? 'Just now' : (count - 1 - i) + 'm ago'), op: 1 };
        });
        return items.slice(-5).map((it, i, arr) => ({ ...it, op: arr.length === 5 && i === 0 ? 0.45 : 1 }));
      })(),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); }
    };
  }
}
