// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    if (consentChoice()) this.setState({ cookieDone: true });
  }
  renderVals() {
    const all = pageData().posts;
    const cat = (this.state && this.state.cat) || 'All posts';
    const PAGE = 12;
    const limit = (this.state && this.state.limit) || PAGE;
    const inCat = all.filter((p) => cat === 'All posts' || p.cat === cat);
    const subbed = !!(this.state && this.state.subbed);
    return {
      feat: pageData().feat,
      cats: ['All posts', ...pageData().cats].map((c) => ({ label: c, pick: () => this.setState({ cat: c, limit: PAGE }), bg: c === cat ? '#232323' : '#FFFFFF', fg: c === cat ? '#FFFFFF' : '#232323', bd: c === cat ? '#232323' : '#E5E3DE' })),
      posts: inCat.slice(0, limit),
      moreShow: inCat.length > limit,
      showMore: () => this.setState({ limit: limit + PAGE }),
      newsError: (this.state && this.state.newsError) || null,
      subbed: subbed, notSubbed: !subbed,
      subscribe: (e) => subscribe(this, e),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); }
    };
  }
}
