// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    if (consentChoice()) this.setState({ cookieDone: true });
    try {
      const ceRow = document.getElementById('ce-row');
      if (ceRow && 'IntersectionObserver' in window) {
        this._ceIo = new IntersectionObserver((es) => es.forEach((e) => e.target.classList.toggle('pc-in', e.intersectionRatio >= 0.55)), { root: ceRow, threshold: [0, 0.55, 1] });
        ceRow.querySelectorAll('.cr-earn').forEach((c) => this._ceIo.observe(c));
      } else document.documentElement.classList.add('no-io');
    } catch (e) { try { document.documentElement.classList.add('no-io'); } catch (x) {} }
    try {
      const rows = Array.prototype.slice.call(document.querySelectorAll('.cr-row'));
      const still = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      if (rows.length && 'IntersectionObserver' in window && !still) {
        this.setState({ frArm: true });
        this._io = new IntersectionObserver((es) => {
          es.forEach((e) => {
            const i = rows.indexOf(e.target); if (i < 0) return;
            const k = 'frIn' + i; const on = !!(this.state && this.state[k]);
            if (e.intersectionRatio >= 0.35 && !on) { this.setState({ [k]: true }); if (i === 2) this.countUp(); }
            else if (!e.isIntersecting && on) this.setState({ [k]: false });
          });
        }, { threshold: [0, 0.35] });
        rows.forEach((r) => this._io.observe(r));
      }
    } catch (e) {}
  }
  componentWillUnmount() { if (this._io) this._io.disconnect(); if (this._ceIo) this._ceIo.disconnect(); }
  countUp() {
    const el = document.querySelector('.frn'); if (!el) return;
    const end = 486, dur = 1300; let t0 = 0;
    el.textContent = '0';
    const tick = (t) => { if (!t0) t0 = t; const p = Math.min(1, (t - t0) / dur); el.textContent = String(Math.round(end * (1 - Math.pow(1 - p, 3)))); if (p < 1) requestAnimationFrame(tick); };
    setTimeout(() => requestAnimationFrame(tick), 250);
  }
  renderVals() {
    const base = [
      { name: 'Ryderwear', logo: '/assets/site/1a95697886757bf99ae3277e71f74287.png', h: '22px' },
      { name: 'CENTRED', logo: '/assets/site/7de170f2efabf62788bf7e3d76ebc57a.png', h: '22px' },
      { name: 'WOLVEN', logo: '/assets/site/7316092ea1127a86c732df63d3690d15.png', h: '30px' },
      { name: 'Proxies', logo: '/assets/site/052de7af66ce41c81c7c37f8ee3029fa.png', h: '26px' },
      { name: 'Kollektif', logo: '/assets/site/c40d5a358e603d352d2afdfbf1b73ca9.png', h: '26px' },
      { name: 'Publik', logo: '/assets/site/55861879c0b984dd02785d5dec196a1f.png', h: '18px' },
      { name: 'Aperitivo Club', logo: '/assets/site/53ee1f604745ec42e5eba9174e44c8e6.png', h: '38px' },
      { name: 'saltee', logo: '/assets/site/4b83a56367c889dd84c9c26cae109c1f.png', h: '32px' },
      { name: 'HIIT Hydration', logo: '/assets/site/5928f7c4381cb011db5d505457e33210.png', h: '18px' },
      { name: 'Osé Active', logo: '/assets/site/a21cc33ae1bbed618ab70a781f23dc01.png', h: '26px' },
      { name: 'BrewHaus', logo: '/assets/site/5007234c753d8476a31ba025c1538cd4.png', h: '24px' }
    ];
    const cats = ['All campaigns', 'Beauty', 'Jewellery', 'Food & Drink', 'Fashion'];
    const cardCat = ['Beauty', 'Jewellery', 'Food & Drink', 'Fashion'];
    const mkCat = (this.state && this.state.mkCat) || 'All campaigns';
    const openFaq = (this.state && typeof this.state.openFaq === 'number') ? this.state.openFaq : 0;
    return {
      brands: base.concat(base).map((b) => ({ ...b, h: Math.round(parseFloat(b.h) * 0.82) + 'px' })),
      mkCats: cats.map((c) => ({ label: c, pick: () => this.setState({ mkCat: c }), bg: c === mkCat ? '#232323' : '#FFFFFF', fg: c === mkCat ? '#FFFFFF' : '#232323', bd: c === mkCat ? '#232323' : '#E5E3DE' })),
      mkD0: mkCat === 'All campaigns' || cardCat[0] === mkCat ? 'block' : 'none',
      mkD1: mkCat === 'All campaigns' || cardCat[1] === mkCat ? 'block' : 'none',
      mkD2: mkCat === 'All campaigns' || cardCat[2] === mkCat ? 'block' : 'none',
      mkD3: mkCat === 'All campaigns' || cardCat[3] === mkCat ? 'block' : 'none',
      faqs: [
        { q: 'Is Linkable free for creators?', a: 'Yes. Creating a profile, applying to campaigns and pitching brands is always free.' },
        { q: 'Do I need a big following?', a: 'No. Brands look for creators who fit their audience, not just the biggest numbers. Many campaigns are open to smaller creators.' },
        { q: 'How do I get paid?', a: 'Commission is tracked through your own link and code and paid out to you. Fixed fees are agreed with each brand before you start.' },
        { q: 'Which platforms can I use?', a: 'Instagram and TikTok. Connect your accounts and your audience insights are added to your profile automatically.' },
        { q: 'What can I pitch?', a: 'Any idea for a brand on Linkable. Set the content, the deliverables and your rate, and the brand replies in your inbox.' },
        { q: 'Who owns the content I make?', a: 'You do. Usage rights are agreed per campaign, so you always know how a brand can use your content.' },
        { q: 'Can I work with brands outside the UK?', a: 'Yes. Brands on Linkable work with creators in many countries, and each campaign shows where it ships.' }
      ].map((f, i) => ({ ...f, open: i === openFaq, toggle: () => this.setState({ openFaq: i === openFaq ? -1 : i }), rot: i === openFaq ? '45deg' : '0deg', iconBg: i === openFaq ? '#232323' : '#F3F2EE', iconFg: i === openFaq ? '#FFFFFF' : '#232323' })),
      fr0: 'cr-row' + (this.state && this.state.frArm ? ' fr-arm' : '') + (this.state && this.state.frIn0 ? ' fr-on' : ''),
      fr1: 'cr-row cr-flip' + (this.state && this.state.frArm ? ' fr-arm' : '') + (this.state && this.state.frIn1 ? ' fr-on' : ''),
      fr2: 'cr-row' + (this.state && this.state.frArm ? ' fr-arm' : '') + (this.state && this.state.frIn2 ? ' fr-on' : ''),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); }
    };
  }
}
