// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    if (consentChoice()) this.setState({ cookieDone: true });
  }
  renderVals() {
    const base = [
      { name: 'Ryderwear', logo: '/assets/site/1a95697886757bf99ae3277e71f74287.png', h: '22px' },
      { name: 'CENTRED', logo: '/assets/site/7de170f2efabf62788bf7e3d76ebc57a.png', h: '22px' },
      { name: 'WOLVEN', logo: '/assets/site/7316092ea1127a86c732df63d3690d15.png', h: '30px' },
      { name: 'Proxies', logo: '/assets/site/052de7af66ce41c81c7c37f8ee3029fa.png', h: '26px' },
      { name: 'Kollektif', logo: '/assets/site/c40d5a358e603d352d2afdfbf1b73ca9.png', h: '26px' },
      { name: 'Publik', logo: '/assets/site/55861879c0b984dd02785d5dec196a1f.png', h: '18px' },
      { name: 'Aperitivo Club', logo: '/assets/site/53ee1f604745ec42e5eba9174e44c8e6.png', h: '38px' },
      { name: 'saltee', logo: '/assets/site/4b83a56367c889dd84c9c26cae109c1f.png', h: '32px' },
      { name: 'HIIT Hydration', logo: '/assets/site/5928f7c4381cb011db5d505457e33210.png', h: '18px' },
      { name: 'Osé Active', logo: '/assets/site/a21cc33ae1bbed618ab70a781f23dc01.png', h: '26px' },
      { name: 'BrewHaus', logo: '/assets/site/5007234c753d8476a31ba025c1538cd4.png', h: '24px' }
    ];
    const yearly = !!(this.state && this.state.yearly);
    const openFaq = (this.state && typeof this.state.openFaq === 'number') ? this.state.openFaq : 0;
    const plans = [
        { name: 'Starter', price: '$99', year: '$990', mo: '$83', blurb: 'For brands getting started with creators.', features: ['Work with up to 10 new creators a month', 'Run up to 2 campaigns at once', 'Campaign and creator insights', 'Dedicated support and onboarding'], bg: '#F6F4EF', fg: '#232323', sub: '#666563', line: '#E8E6E1', popular: false, btnClass: 'btn btn-primary btn-arrow' },
        { name: 'Growth', price: '$199', year: '$1,990', mo: '$166', blurb: 'For brands working with creators every month.', features: ['Work with up to 50 new creators a month', 'Run up to 10 campaigns at once', 'Campaign and creator insights', 'Dedicated support and onboarding'], bg: '#232323', fg: '#FFFFFF', sub: '#B5B3AE', line: '#3A3A38', popular: true, btnClass: 'btn btn-ghost btn-arrow' },
        { name: 'Scale', price: '$499', year: '$4,990', mo: '$416', blurb: 'For brands running a full creator program.', features: ['Work with up to 100 new creators a month', 'Run up to 20 campaigns at once', 'Advanced campaign and creator insights', 'Priority support and onboarding'], bg: '#F6F4EF', fg: '#232323', sub: '#666563', line: '#E8E6E1', popular: false, btnClass: 'btn btn-primary btn-arrow' }
      ].map((p) => ({ ...p, shown: yearly ? p.mo : p.price, note: yearly ? 'Billed ' + p.year + ' a year' : 'or ' + p.year + ' a year, save 17%' }));
    return {
      brands: base.concat(base),
      plans: plans,
      cmp0: plans[0].shown, cmp1: plans[1].shown, cmp2: plans[2].shown,
      setMonthly: () => this.setState({ yearly: false }),
      setYearly: () => this.setState({ yearly: true }),
      mBg: yearly ? 'transparent' : '#FFFFFF', mFg: yearly ? '#666563' : '#232323', mSh: yearly ? 'none' : '0 1px 3px rgba(35,35,35,.12)',
      yBg: yearly ? '#FFFFFF' : 'transparent', yFg: yearly ? '#232323' : '#666563', ySh: yearly ? '0 1px 3px rgba(35,35,35,.12)' : 'none',
      faqs: [
        { q: 'How does the free trial work?', a: 'Every plan is free for the first 30 days, with full access to the platform. Change plan or cancel any time.' },
        { q: 'Can I change plan later?', a: 'Yes. Move up or down a plan, or cancel, whenever you need to.' },
        { q: 'What counts towards my monthly creator limit?', a: 'Each new creator you start working with in a month counts once. Applications and invitations are unlimited on every plan.' },
        { q: 'What is the 2.5% fee?', a: 'It applies only to sales tracked through creator links and codes. Every other sale in your store carries no fee.' },
        { q: 'How does yearly billing work?', a: 'Pay once a year and save 17% compared with paying monthly.' },
        { q: 'Which currency are prices in?', a: 'Prices are in US dollars.' },
        { q: 'Do I need a Shopify store?', a: 'No. Linkable works without Shopify. Connect it when you want product sync, discount codes and sales attribution.' },
        { q: 'How much does the managed service cost?', a: 'It depends on the campaigns you want us to run. Talk to our team and we’ll put together a plan for your brand.' }
      ].map((f, i) => ({ ...f, open: i === openFaq, toggle: () => this.setState({ openFaq: i === openFaq ? -1 : i }), rot: i === openFaq ? '45deg' : '0deg', iconBg: i === openFaq ? '#232323' : '#F3F2EE', iconFg: i === openFaq ? '#FFFFFF' : '#232323' })),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); }
    };
  }
}
