// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    if (consentChoice()) this.setState({ cookieDone: true });
  }
  renderVals() {
    const creator = !!(this.state && this.state.creator);
    const sent = !!(this.state && this.state.sent);
    const on = '#FFFFFF', off = 'transparent', sh = '0 1px 3px rgba(35,35,35,.12)';
    return {
      asBrand: () => this.setState({ creator: false, error: null }),
      asCreator: () => this.setState({ creator: true, error: null }),
      bBg: creator ? off : on, bFg: creator ? '#666563' : '#232323', bSh: creator ? 'none' : sh,
      cBg: creator ? on : off, cFg: creator ? '#232323' : '#666563', cSh: creator ? sh : 'none',
      thirdLabel: creator ? 'Instagram or TikTok handle' : 'Company website',
      thirdPh: creator ? '@yourhandle' : 'yourbrand.com',
      msgPh: creator ? 'Tell us what you need help with.' : 'Tell us about your brand and what you want to achieve with creators.',
      sent: sent, notSent: !sent, error: (this.state && this.state.error) || null, busy: !!(this.state && this.state.busy),
      send: (e) => sendContact(this, e),
      reset: () => this.setState({ sent: false }),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); }
    };
  }
}
