// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    if (consentChoice()) this.setState({ cookieDone: true });
    try {
      const bar = document.querySelector('.ps-progress span');
      const art = document.querySelector('.ps-body');
      const heads = Array.prototype.slice.call(document.querySelectorAll('.ps-body h2'));
      if (!art) return;
      this._onScroll = () => {
        const r = art.getBoundingClientRect();
        const total = r.height - window.innerHeight + 240;
        const p = Math.max(0, Math.min(1, (120 - r.top) / (total > 0 ? total : 1)));
        if (bar) bar.style.transform = 'scaleX(' + p + ')';
        let a = -1;
        heads.forEach((h, i) => { if (h.getBoundingClientRect().top < 160) a = i; });
        if (a !== ((this.state && typeof this.state.toc === 'number') ? this.state.toc : -1)) this.setState({ toc: a });
      };
      window.addEventListener('scroll', this._onScroll, { passive: true });
      this._onScroll();
    } catch (e) {}
  }
  componentWillUnmount() { if (this._onScroll) window.removeEventListener('scroll', this._onScroll); }
  renderVals() {
    const t = (this.state && typeof this.state.toc === 'number') ? this.state.toc : -1;
    const { post, related } = pageData();
    const copied = !!(this.state && this.state.copied);
    return {
      post, related,
      toc: post.toc.map((x, i) => ({ ...x, cls: i === t ? 'on' : '' })),
      copyLabel: copied ? 'Link copied' : 'Copy link',
      copyLink: (e) => copyLink(this, e, post.url),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); }
    };
  }
}
