// Generated by tools/design/import.py from the design export; do not edit by hand.
import { DCLogic, pageData } from '../../runtime.js';
import { copyLink, sendContact, subscribe } from '../../actions.js';
import { acceptAll, consentChoice, rejectAll } from '../../../consent.js';

export class PageLogic extends DCLogic {
  componentDidMount() {
    try {
      const cv = document.getElementById('ap-cloud');
      if (cv && cv.getContext) {
        const dpr = window.devicePixelRatio || 1;
        cv.width = 320 * dpr; cv.height = 160 * dpr;
        const ctx = cv.getContext('2d'); ctx.scale(dpr, dpr);
        const nodes = [];
        const rings = [[34, 8], [56, 13], [76, 17]];
        rings.forEach(([r, n], ri) => { for (let i = 0; i < n; i++) nodes.push({ r: r, a: (i / n) * Math.PI * 2 + ri * 0.4 + Math.random() * 0.3, sp: (ri % 2 ? -1 : 1) * (0.00012 + ri * 0.00004), s: 2.2 + Math.random() * 1.6 }); });
        const links = [];
        let lastPick = 0;
        let still = false;
        try { still = window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}
        const draw = (t) => {
          ctx.clearRect(0, 0, 320, 160);
          const cx = 160, cy = 80;
          if (!still && t - lastPick > 650) { lastPick = t; links.push({ i: Math.floor(Math.random() * nodes.length), t0: t }); if (links.length > 6) links.shift(); }
          const pos = nodes.map((n) => { const a = n.a + (still ? 0 : t * n.sp); return [cx + Math.cos(a) * n.r * 1.9, cy + Math.sin(a) * n.r * 0.95]; });
          ctx.lineWidth = 1;
          for (const l of links) {
            const age = (t - l.t0) / 2600; if (age > 1) continue;
            const p = pos[l.i], grow = Math.min(1, age * 3);
            ctx.globalAlpha = (1 - age) * 0.55; ctx.strokeStyle = '#232323';
            ctx.beginPath(); ctx.moveTo(p[0], p[1]); ctx.lineTo(p[0] + (cx - p[0]) * grow, p[1] + (cy - p[1]) * grow); ctx.stroke();
          }
          nodes.forEach((n, i) => {
            const lk = links.find((l) => l.i === i && (t - l.t0) < 2600);
            ctx.globalAlpha = lk ? 1 : 0.32; ctx.fillStyle = lk ? '#22B566' : '#232323';
            ctx.beginPath(); ctx.arc(pos[i][0], pos[i][1], lk ? n.s + 1 : n.s, 0, Math.PI * 2); ctx.fill();
          });
          const pulse = still ? 0 : (Math.sin(t * 0.003) + 1) / 2;
          ctx.globalAlpha = 0.12 * (1 - pulse); ctx.fillStyle = '#232323';
          ctx.beginPath(); ctx.arc(cx, cy, 12 + pulse * 10, 0, Math.PI * 2); ctx.fill();
          ctx.globalAlpha = 1; ctx.fillStyle = '#232323';
          ctx.beginPath(); ctx.arc(cx, cy, 9, 0, Math.PI * 2); ctx.fill();
          if (!still) this._apRaf = requestAnimationFrame(draw);
        };
        this._apRaf = requestAnimationFrame(draw);
      }
    } catch (e) {}
    if (consentChoice()) this.setState({ cookieDone: true });
    try {
      this._onScroll = () => {
        const el = document.getElementById('ways-track');
        if (!el || window.innerWidth <= 960) return;
        const scrollable = document.documentElement.scrollHeight > window.innerHeight + 400;
        if (scrollable !== !!(this.state && this.state.scrollMode)) this.setState({ scrollMode: scrollable });
        if (!scrollable) return;
        const r = el.getBoundingClientRect();
        const total = el.offsetHeight - window.innerHeight;
        if (total <= 0) return;
        const prog = Math.min(Math.max(-r.top / total, 0), 0.9999);
        const idx = Math.floor(prog * 4);
        if (!this.state || this.state.scrollIdx !== idx) this.setState({ scrollIdx: idx });
      };
      // scroll pinning disabled for now
    } catch (e) {}
    let reduce = false;
    try { reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}
    try {
      [].forEach(([tid, rid]) => {
      const track = document.getElementById(tid), row = document.getElementById(rid);
      if (track && row) {
        const fit = () => {
          if (window.innerWidth > 760) { track.style.height = ''; row.style.transform = ''; return; }
          const extra = Math.max(0, row.scrollWidth - window.innerWidth + 16);
          track.style.height = (row.parentNode.offsetHeight + extra) + 'px';
          track._extra = extra;
        };
        const move = () => {
          if (window.innerWidth > 760) return;
          const r = track.getBoundingClientRect();
          const p = Math.max(0, Math.min(1, (76 - r.top) / Math.max(1, track._extra || 1)));
          row.style.transform = 'translate3d(' + (-p * (track._extra || 0)) + 'px,0,0)';
        };
        const refit = () => { fit(); move(); };
        fit(); move();
        (this._sc = this._sc || []).push([move, refit]);
        window.addEventListener('scroll', move, { passive: true });
        window.addEventListener('resize', refit);
        setTimeout(refit, 600); setTimeout(refit, 1800);
      }
      });
    } catch (e) {}
    try {
      if ('IntersectionObserver' in window) {
        [['pg-row', '.plat-card'], ['wm-row', '.wm-card']].forEach(([rid, sel]) => {
          const row = document.getElementById(rid); if (!row) return;
          const io = new IntersectionObserver((es) => es.forEach((e) => e.target.classList.toggle('pc-in', e.intersectionRatio >= 0.55)), { root: row, threshold: [0, 0.55, 1] });
          row.querySelectorAll(sel).forEach((c) => io.observe(c));
          (this._ios = this._ios || []).push(io);
        });
      } else { document.documentElement.classList.add('no-io'); }
    } catch (e) { try { document.documentElement.classList.add('no-io'); } catch (x) {} }
    if (reduce) { this.setState({ reduced: true }); return; }
    if (window.innerWidth <= 760) {
      this.setState({ mobile: true });
      const how = document.getElementById('how');
      if (how && 'IntersectionObserver' in window) {
        const hio = new IntersectionObserver((es) => {
          es.forEach((e) => {
            if (e.isIntersecting && !this._timer) {
              this._timer = setInterval(() => { this.setState({ tick: ((this.state && this.state.tick) || 0) + 1 }); }, 1600);
            } else if (!e.isIntersecting && this._timer) { clearInterval(this._timer); this._timer = null; }
          });
        }, { threshold: 0.05 });
        hio.observe(how);
        (this._ios = this._ios || []).push(hio);
      }
      return;
    }
    this._timer = setInterval(() => {
      this.setState({ tick: ((this.state && this.state.tick) || 0) + 1 });
    }, 1600);
  }
  componentWillUnmount() {
    if (this._timer) clearInterval(this._timer);
    if (this._apRaf) cancelAnimationFrame(this._apRaf);
    (this._ios || []).forEach((o) => o.disconnect());
    (this._sc || []).forEach(([m, r]) => { window.removeEventListener('scroll', m); window.removeEventListener('resize', r); });
    if (this._onScroll) { window.removeEventListener('scroll', this._onScroll); window.removeEventListener('resize', this._onScroll); }
  }
  renderVals() {
    const serif = "'Fraunces', Georgia, serif";
    const sans = "'Manrope', system-ui, sans-serif";
    const base = [
      { name: 'Ryderwear', logo: '/assets/site/1a95697886757bf99ae3277e71f74287.png', h: '22px' },
      { name: 'CENTRED', logo: '/assets/site/7de170f2efabf62788bf7e3d76ebc57a.png', h: '22px' },
      { name: 'WOLVEN', logo: '/assets/site/7316092ea1127a86c732df63d3690d15.png', h: '30px' },
      { name: 'Proxies', logo: '/assets/site/052de7af66ce41c81c7c37f8ee3029fa.png', h: '26px' },
      { name: 'Kollektif', logo: '/assets/site/c40d5a358e603d352d2afdfbf1b73ca9.png', h: '26px' },
      { name: 'Publik', logo: '/assets/site/55861879c0b984dd02785d5dec196a1f.png', h: '18px' },
      { name: 'Aperitivo Club', logo: '/assets/site/53ee1f604745ec42e5eba9174e44c8e6.png', h: '38px' },
      { name: 'saltee', logo: '/assets/site/4b83a56367c889dd84c9c26cae109c1f.png', h: '32px' },
      { name: 'HIIT Hydration', logo: '/assets/site/5928f7c4381cb011db5d505457e33210.png', h: '18px' },
      { name: 'Osé Active', logo: '/assets/site/a21cc33ae1bbed618ab70a781f23dc01.png', h: '26px' },
      { name: 'BrewHaus', logo: '/assets/site/5007234c753d8476a31ba025c1538cd4.png', h: '24px' }
    ];
    const tick = (this.state && this.state.tick) || 0;
    const reduced = !!(this.state && this.state.reduced);
    const niche = (this.state && this.state.niche) || 'All creators';
    const hoverWay = (this.state && this.state.hoverWay) || null;
    const wayPick = (this.state && typeof this.state.wayPick === 'number') ? this.state.wayPick : null;
    const scrollMode = false;
    const scrollIdx = (this.state && typeof this.state.scrollIdx === 'number') ? this.state.scrollIdx : 0;
    const wayIdx = wayPick !== null ? wayPick : 0;
    const yearly = !!(this.state && this.state.yearly);
    const openFaq = (this.state && typeof this.state.openFaq === 'number') ? this.state.openFaq : 0;
    const still = reduced || !!(this.state && this.state.mobile);
    const wPhase = still ? 0 : Math.floor(tick / 2) % 4;
    const miaDone = wPhase >= 2;
    const askMode = wPhase === 1 || wPhase === 2;
    const codeUses = still ? 41 : 41 + Math.floor(tick / 3);
    const feeOpt = (on) => on
      ? { bg: '#F3F2EE', bd: '#CFCCC5', fw: 600, fg: '#232323', ring: '4px solid #232323' }
      : { bg: '#FFFFFF', bd: '#ECEAE5', fw: 500, fg: '#666563', ring: '1.5px solid #CFCCC5' };
    const nicheList = ['All creators', 'Beauty', 'Wellness', 'Fitness', 'Lifestyle', 'Food & Drink', 'Fashion'];
    const creatorList = [
      { name: 'Sofia M.', city: 'London, UK', tags: ['Beauty', 'Skincare', 'Lifestyle'], eng: '4.8%', followers: '248K', views: '32K', photo: '/assets/site/9ee13537026be94c23d8f3ff27d01c21.jpg', thumbs: ['/assets/site/4140cd690b8c94548d03a1f6ad0b5a91.jpg', '/assets/site/5211fa4c363dd80d0487076a0a88baaa.jpg', '/assets/site/8ab0bf7546d0d73e4863716c42a8d5e0.jpg'] },
      { name: 'Tom H.', city: 'Manchester, UK', tags: ['Fitness', 'Wellness', 'Lifestyle'], eng: '6.1%', followers: '120K', views: '18K', photo: '/assets/site/56b44078bd50090d765f675c5316889e.jpg', thumbs: ['/assets/site/a12774ed665e7b304e80de452cc3962b.jpg', '/assets/site/50e423476876f107a7371334a88f101c.jpg', '/assets/site/de7b57592a28410fc8f63cb6f539b0c2.jpg'] },
      { name: 'Grace R.', city: 'Brighton, UK', tags: ['Food & Drink', 'Wellness', 'Lifestyle'], eng: '3.9%', followers: '86K', views: '11K', photo: '/assets/site/dcfbd6a0875a0baa6ef7cfd6c7f6a8b0.jpg', thumbs: ['/assets/site/edb8e4960878d9a522163f529090ba81.jpg', '/assets/site/1ca3de47edc7c2ab079864314fc94d03.jpg', '/assets/site/3acadc33b790ab86775d220fda492d1d.jpg'] },
      { name: 'Naomi L.', city: 'London, UK', tags: ['Fashion', 'Lifestyle', 'Beauty'], eng: '5.2%', followers: '310K', views: '41K', photo: '/assets/site/3e142287963788eaaac9cf9cf8385d11.jpg', thumbs: ['/assets/site/7988faf653e9b58c0a33f109daa3234d.jpg', '/assets/site/f233528c4977d1c42f6d6550d7a5d35b.jpg', '/assets/site/218b89d8d87ded905723339b74a09bc8.jpg'] },
      { name: 'Luca B.', city: 'Bristol, UK', tags: ['Travel', 'Outdoor', 'Lifestyle'], eng: '4.1%', followers: '62K', views: '9K', photo: '/assets/site/483c0bea8e706fa58d093ca5818daa2f', thumbs: ['/assets/site/efc8172f50611a3bbdebeadc274322ed', '/assets/site/208fd790ee10d295cddbbb83682a5717', '/assets/site/2f19f0059651af113bb1cb406234c143'] }
    ];
    const seq = [[0, 0], [1, 0], [1, 1], [2, 1], [2, 0], [0, 1]];
    const collab = seq[tick % seq.length][0];
    const goal = seq[tick % seq.length][1];
    const opt = (on) => on
      ? { bg: '#F3F2EE', bd: '#CFCCC5', fg: '#232323', fw: 500 }
      : { bg: '#FFFFFF', bd: '#ECEAE5', fg: '#666563', fw: 400 };
    const content = ['/assets/site/282df7f07cadd350e4668517a7b798d4.jpg', '/assets/site/a86660e3e823b9294e4b1bbf13de8993.jpg', '/assets/site/006553a0c7d01ba2540f51addeca2f25.jpg'];
    const navItems = [
      { label: 'Home', icon: 'M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-6h-6v6H4a1 1 0 0 1-1-1z' },
      { label: 'Campaigns', icon: 'M4 7h16v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zM9 7V5a3 3 0 0 1 6 0v2', active: true },
      { label: 'Discover', icon: 'M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14zM21 21l-4.3-4.3' },
      { label: 'Messages', icon: 'M4 5h16v11H8l-4 4z', badge: '3' },
      { label: 'Content', icon: 'M4 4h16v16H4zM4 15l5-5 4 4 3-3 4 4' },
      { label: 'Analytics', icon: 'M5 20V11M12 20V5M19 20v-7' },
      { label: 'Payouts', icon: 'M3 6h18v12H3zM3 10h18M7 15h3' }
    ];
    return {
      nav: navItems.map((n) => ({ ...n, badge: n.badge || null, bg: n.active ? '#F3F2EE' : 'transparent', color: n.active ? '#232323' : '#666563', weight: n.active ? 600 : 400 })),
      kpis: [
        { value: '247', label: 'Applications', delta: '32%' },
        { value: '32', label: 'Approved', delta: '12%' },
        { value: '28', label: 'Content pieces', delta: '40%' },
        { value: '284K', label: 'Total reach', delta: '32%' }
      ],
      apps: [
        { img: '/assets/site/e9742b9f0458267dad8898ce6202cb59.jpg', name: 'Sophie L.', handle: '@sophielaurem', followers: '284K followers', t1: 'Beauty', t2: 'Skincare', content },
        { img: '/assets/site/a4c01baa144c650adf451ba495665bcd.jpg', name: 'Marco R.', handle: '@marcorossi', followers: '94K followers', t1: 'Lifestyle', t2: 'Wellness', content: [content[1], content[2], content[0]] },
        { img: '/assets/site/cd18dc14c7998c6570e30910ac121a8b.jpg', name: 'Emma T.', handle: '@emmatravels', followers: '62K followers', t1: 'Beauty', t2: 'Lifestyle', content: [content[2], content[0], content[1]] }
      ],
      miaText: miaDone ? 'Delivered' : 'In transit',
      miaBg: miaDone ? '#EAF7EF' : '#F3F2EE',
      miaFg: miaDone ? '#168A4C' : '#666563',
      feeA: feeOpt(!askMode),
      feeB: feeOpt(askMode),
      codeUses: codeUses,
      hoverGift: () => this.setState({ hoverWay: 'gift' }),
      setMonthly: () => this.setState({ yearly: false }),
      setYearly: () => this.setState({ yearly: true }),
      mBg: yearly ? 'transparent' : '#FFFFFF', mFg: yearly ? '#666563' : '#232323', mSh: yearly ? 'none' : '0 1px 3px rgba(35,35,35,.12)',
      yBg: yearly ? '#FFFFFF' : 'transparent', yFg: yearly ? '#232323' : '#666563', ySh: yearly ? '0 1px 3px rgba(35,35,35,.12)' : 'none',
      hoverPaid: () => this.setState({ hoverWay: 'paid' }),
      hoverAff: () => this.setState({ hoverWay: 'aff' }),
      hoverOff: () => this.setState({ hoverWay: null }),
      mixOpts: [
        { key: 'gift', label: 'Free product', base: true },
        { key: 'paid', label: 'Payment', base: false },
        { key: 'aff', label: 'Commission', base: true }
      ].map((m) => {
        const hot = hoverWay === m.key;
        const on = m.base || hot;
        return {
          label: m.label, on,
          bg: on ? '#F3F2EE' : '#FFFFFF', bd: hot ? '#232323' : (on ? '#CFCCC5' : '#ECEAE5'),
          ring: hot ? '0 0 0 3px rgba(35,35,35,.08)' : 'none',
          fw: on ? 500 : 400, fg: on ? '#232323' : '#666563',
          boxBg: on ? '#232323' : '#FFFFFF', boxBd: on ? '0' : '1.5px solid #CFCCC5'
        };
      }),
      platCreators: [
        { img: '/assets/site/28e6a9a592897d051a983a76237125e3.jpg', handle: '@ellathompson', meta: '182K followers · 4.8% ER' },
        { img: '/assets/site/d3a871b40b9d03ede4a437dd568b13a6.jpg', handle: '@jamestaylor', meta: '89K followers · 3.9% ER' },
        { img: '/assets/site/e9742b9f0458267dad8898ce6202cb59.jpg', handle: '@sophielaurem', meta: '284K followers · 5.1% ER' }
      ].map((p, i) => ({ ...p, line: i === 0 ? '0' : '1px solid #F0EEEA' })),
      platContent: [
        { img: '/assets/site/d7af668480bb4be90c3e47de0162d131.jpg', views: '12.4K' },
        { img: '/assets/site/a86660e3e823b9294e4b1bbf13de8993.jpg', views: '8.1K' },
        { img: '/assets/site/282df7f07cadd350e4668517a7b798d4.jpg', views: '5.6K' },
        { img: '/assets/site/006553a0c7d01ba2540f51addeca2f25.jpg', views: '34.2K' }
      ],
      platPayouts: [
        { img: '/assets/site/e9742b9f0458267dad8898ce6202cb59.jpg', handle: '@sophielaurem', meta: '14 sales · £48.20' },
        { img: '/assets/site/0b01b160de2ef07bc1ee2726a517553b.jpg', handle: '@mianose', meta: '9 sales · £31.50' }
      ],
      platApps: [
        { img: '/assets/site/87b45fd0cb05693b5656283cc9b34690.jpg', name: 'Sofia M.', meta: 'Beauty · 248K', state: 'done' },
        { img: '/assets/site/dcfbd6a0875a0baa6ef7cfd6c7f6a8b0.jpg', name: 'Grace R.', meta: 'Wellness · 86K', state: 'open' },
        { img: '/assets/site/f0065530efafa045d283aebbbe735daf', name: 'Naomi L.', meta: 'Lifestyle · 310K', state: 'open' }
      ].map((a, i) => ({ ...a, done: a.state === 'done', open: a.state === 'open', line: i === 0 ? '0' : '1px solid #F0EEEA' })),
      platShips: [
        { img: '/assets/site/e9742b9f0458267dad8898ce6202cb59.jpg', name: 'Sophie L.', status: 'Delivered', chipBg: '#EAF7EF', chipFg: '#168A4C', s2: '#22B566', s3: '#22B566' },
        { img: '/assets/site/0b01b160de2ef07bc1ee2726a517553b.jpg', name: 'Mia R.', status: 'In transit', chipBg: '#F3F2EE', chipFg: '#666563', s2: '#22B566', s3: '#E8E6E1' }
      ].map((s, i) => ({ ...s, line: i === 0 ? '0' : '1px solid #F0EEEA' })),
      platProducts: [
        { img: '/assets/site/965740eae8a5a81808529e3dc68a80ad.jpg', name: 'Vitamin C Serum', meta: '£24.00 · 86 in stock', camp: '2 campaigns' },
        { img: '/assets/site/9b6e419b4a2c59d9374660a3eaff465f.jpg', name: 'Electrolyte Blend', meta: '£32.00 · 140 in stock', camp: '1 campaign' },
        { img: '/assets/site/488756292311e242fa53c06256d1c149.jpg', name: 'Protein Bar', meta: '£2.50 · 410 in stock', camp: '1 campaign' }
      ],
      niches: nicheList.map((n) => {
        const on = n === niche;
        return { label: n, pick: () => this.setState({ niche: n }), bg: on ? '#232323' : '#FFFFFF', fg: on ? '#FFFFFF' : '#232323', bd: on ? '#232323' : '#E5E3DE' };
      }),
      creators: creatorList.filter((c) => niche === 'All creators' || c.tags.indexOf(niche) !== -1).slice(0, 4),
      trust: [
        { title: 'Verified creators', body: 'Real profiles, real audiences', icon: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75' },
        { title: 'Worldwide reach', body: 'Work with creators anywhere', icon: 'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z' },
        { title: 'All niches', body: 'From beauty to fitness and more', icon: 'M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9zM19 3v4M17 5h4M5 17v3M3.5 18.5h3' },
        { title: 'Reviewed by brands', body: 'See ratings from past collaborations', icon: 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zM9 12l2 2 4-4' }
      ],
      steps: [
        { n: 1, title: 'Create your campaign', body: 'Add your product, choose Gifted, Paid or Affiliate, and set your goals, audience and campaign details.', native1: true },
        { n: 2, title: 'Connect with the right creators', body: 'Relevant creators can apply to your campaign, or you can discover and invite creators directly. You choose who to work with.', native2: true, rows: [
          { img: '/assets/site/28e6a9a592897d051a983a76237125e3.jpg', name: 'Ella T.', match: '98% match', sub: 'Beauty · 182K followers · UK' },
          { img: '/assets/site/e9742b9f0458267dad8898ce6202cb59.jpg', name: 'Sophie L.', match: '95% match', sub: 'Skincare · 284K followers · UK' },
          { img: '/assets/site/0b01b160de2ef07bc1ee2726a517553b.jpg', name: 'Mia R.', match: '92% match', sub: 'Lifestyle · 120K followers · US' }
        ].map((r, i, all) => {
          const shown = reduced ? all.length : Math.min(1 + (tick % 4), all.length);
          const on = i < shown;
          return { ...r, op: on ? 1 : 0, ty: on ? '0' : '-8px', line: i === 0 ? '0' : '1px solid #F0EEEA' };
        }), newCount: reduced ? 3 : Math.min(1 + (tick % 4), 3) },
        { n: 3, title: 'Collaborate & grow', body: 'Manage samples, content, tracking and payouts in one place, and see the real results from your creator collaborations.', native3: true,
          delivered: reduced ? 4 : 1 + (tick % 4),
          thumbs: [
            { img: '/assets/site/d7af668480bb4be90c3e47de0162d131.jpg', badge: '/assets/site/dd5baa8cb08da03aac7d075ae4d91b8a.png' },
            { img: '/assets/site/a86660e3e823b9294e4b1bbf13de8993.jpg', badge: '/assets/site/1c007a5e94d98ccd50f1412b646a785a.png' },
            { img: '/assets/site/282df7f07cadd350e4668517a7b798d4.jpg', badge: '/assets/site/dd5baa8cb08da03aac7d075ae4d91b8a.png' },
            { img: '/assets/site/006553a0c7d01ba2540f51addeca2f25.jpg', badge: '/assets/site/1c007a5e94d98ccd50f1412b646a785a.png' }
          ].map((t, i) => {
            const on = reduced || i < 1 + (tick % 4);
            return { ...t, op: on ? 1 : 0, sc: on ? 1 : 0.94 };
          }) }
      ].map((s) => ({ ...s, img: s.img || null, alt: s.alt || '', native1: !!s.native1, native2: !!s.native2, rows: s.rows || [], native3: !!s.native3, thumbs: s.thumbs || [], delivered: s.delivered || 0, noImg: !s.img && !s.native1 && !s.native2 && !s.native3, o0: opt(collab === 0), o1: opt(collab === 1), o2: opt(collab === 2), g0: opt(goal === 0), g1: opt(goal === 1) })),
      stars: [1, 2, 3, 4, 5],
      metrics: [
        { value: '284K', label: 'Views', delta: '72%', border: '0' },
        { value: '18.6K', label: 'Clicks', delta: '48%', border: '1px solid #ECEAE5' },
        { value: '£12,480', label: 'Revenue', delta: '67%', border: '1px solid #ECEAE5' }
      ],
      brands: base.concat(base).map((b) => ({ ...b, logo: b.logo || null, isText: !b.logo, h: b.h ? Math.round(parseFloat(b.h) * 0.82) + 'px' : b.h })),
      stats: [
        { value: '91%', label: 'approve a creator within 7 days' },
        { value: '<1h', label: 'to the first application' },
        { value: '3.5×', label: 'more content than traditional creator sourcing' },
        { value: '175+', label: 'countries in our creator network' }
      ],
      managed: ['Samples and shipping', 'Deliverables', 'Content uploads', 'Usage rights', 'Discount codes', 'Sales attribution', 'Commissions', 'Creator payouts'],
      ways: [
        { name: 'Gifted', icon: 'M20 12v9H4v-9M2 7h20v5H2zM12 22V7M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7zM12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z', body: 'Send free product to the creators you approve. They create and share content featuring it.', give: 'Free product', get: ['Brand awareness', 'Organic content', 'Product seeding', 'Reviews and unboxings'], best: 'building a content library', img: '/assets/site/805a37b5a4a7d21d3c5ca41108d60d5e.jpg', alt: 'Creator applying a gifted serum', pos: '50% 28%', thumb: '/assets/site/d644117d12fda0737df27a8bcb000da0.jpg', chipTitle: 'Clarifying Serum', chipSub: 'Shipped to 12 creators', chipTag: 'Delivered' },
        { name: 'Paid', icon: 'M2 5h20v14H2zM2 10h20', body: 'Pay a set fee for agreed content, or let creators propose their own rate when they apply.', give: 'A set fee', get: ['Assets for paid media', 'High quality content', 'Larger creators', 'Guaranteed deliverables'], best: 'ad creative and launches', img: '/assets/site/1896fe808a281f4c712f65fa80512594.jpg', alt: 'Creator wearing gold drop earrings', thumb: '/assets/site/75163011673c0bce90e5473c56500d66.jpg', chipTitle: 'Gold Drop Earrings', chipSub: '£100 per creator · 1 Reel', chipTag: 'Fee agreed' },
        { name: 'Affiliate', icon: 'M19 5 5 19M6.5 4a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM17.5 15a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5z', body: 'Creators earn commission on every sale they drive, with their own link and discount code.', give: 'Commission on sales', get: ['Sales', 'Testing new creators', 'Ongoing promotion', 'No upfront cost'], best: 'testing creators at no upfront cost', img: '/assets/site/065139893da1a2a2d8434306736e52a6.jpg', alt: 'Creators running together', thumb: '/assets/site/488756292311e242fa53c06256d1c149.jpg', chipTitle: 'LEO15 · 15% off', chipSub: 'Protein Bar · 15% commission', chipTag: 'Used ' + codeUses + '×' },
        { name: 'Mix them', icon: 'M8 3H3v5M3 3l7 7M16 3h5v5M21 3l-7 7M8 21H3v-5M3 21l7-7M16 21h5v-5M21 21l-7-7', give: 'Any combination', get: ['Awareness and sales', 'Content at scale', 'Rewarding top creators', 'Flexible budgets'], img: '/assets/site/ec74e10b8d5abdfdc40051f8e07db321.jpg', alt: 'Creator wearing black sunglasses in the sun', pos: '50% 74%', mpos: '50% 100%', thumb: '/assets/site/a54f2d8307a9552b5e70bbd8df73710e.jpg', chipTitle: 'Black Rectangle Sunglasses', chipSub: 'Free product + 15% commission', chipTag: 'Live' }
      ].map((w, i) => ({ ...w, pos: w.pos || '50% 50%', mpos: w.mpos || w.pos || '50% 50%', sc: i === wayIdx ? 1 : 1.07, on: i === wayIdx, op: i === wayIdx ? 1 : 0, pick: () => {
          if (scrollMode) {
            const el = document.getElementById('ways-track');
            const top = el.getBoundingClientRect().top + window.scrollY;
            const total = el.offsetHeight - window.innerHeight;
            window.scrollTo({ top: top + total * (i + 0.5) / 4, behavior: 'smooth' });
          } else { this.setState({ wayPick: i }); }
        }, bg: i === wayIdx ? '#FFFFFF' : 'transparent', sh: i === wayIdx ? '0 12px 32px rgba(35,35,35,.08)' : 'none', bd: i === wayIdx ? '#ECEAE5' : 'transparent', iconBg: i === wayIdx ? '#232323' : '#F3F2EE', iconFg: i === wayIdx ? '#FFFFFF' : '#232323' })),
      waysPad: scrollMode ? '0' : '120px 0 72px',
      waysTrackH: scrollMode ? '2400px' : 'auto',
      waysPos: scrollMode ? 'sticky' : 'relative',
      waysInnerPad: scrollMode ? '88px 0 24px' : '0',
      waysMode: scrollMode ? 'ways-pinned' : '',
      demoOn: !!(this.state && this.state.demoOn),
      demoIdle: !(this.state && this.state.demoOn),
      playDemo: (e) => { try { e && e.preventDefault && e.preventDefault(); } catch (x) {} this.setState({ demoOn: true }); },
      stopDemo: () => this.setState({ demoOn: false }),
      nicheRowClass: 'niche-row' + (this.state && this.state.nicheOpen ? ' open' : ''),
      nicheMoreLabel: (this.state && this.state.nicheOpen) ? 'Show less' : '+5 more',
      toggleNiches: () => this.setState({ nicheOpen: !(this.state && this.state.nicheOpen) }),
      cookieShow: !(this.state && this.state.cookieDone),
      cookieAccept: () => { acceptAll(); this.setState({ cookieDone: true }); },
      cookieReject: () => { rejectAll(); this.setState({ cookieDone: true }); },
      apFeed: (() => {
        const steps = [
          'Campaign drafted from your product page',
          'Brief and deliverables written',
          'Sourced 48 creators who fit your brand',
          'Top 12 matched by audience and engagement',
          'Invites sent with your offer',
          'Shipping arranged for approved creators',
          'Follow ups sent to keep content on time'
        ];
        const phase = still ? steps.length : tick % (steps.length + 3);
        const count = Math.min(phase + 1, steps.length);
        const allDone = phase >= steps.length;
        const items = steps.slice(0, count).map((t, i) => {
          const run = !allDone && i === count - 1;
          return { text: t, run: run, done: !run, icBg: run ? 'transparent' : '#FFFFFF', when: run ? 'Now' : (count - 1 - i === 0 ? 'Just now' : (count - 1 - i) + 'm ago'), op: 1 };
        });
        return items.slice(-5).map((it, i, arr) => ({ ...it, op: arr.length === 5 && i === 0 ? 0.45 : 1 }));
      })(),
      wG: wayIdx === 0, wP: wayIdx === 1, wA: wayIdx === 2, wM: wayIdx === 3,
      wayNow: [
        { thumb: '/assets/site/d644117d12fda0737df27a8bcb000da0.jpg', chipTitle: 'Clarifying Serum', chipSub: 'Shipped to 12 creators', chipTag: 'Delivered' },
        { thumb: '/assets/site/75163011673c0bce90e5473c56500d66.jpg', chipTitle: 'Gold Drop Earrings', chipSub: '£100 per creator · 1 Reel', chipTag: 'Fee agreed' },
        { thumb: '/assets/site/488756292311e242fa53c06256d1c149.jpg', chipTitle: 'LEO15 · 15% off', chipSub: 'Protein Bar · 15% commission', chipTag: 'Used ' + codeUses + '×' },
        { thumb: '/assets/site/a54f2d8307a9552b5e70bbd8df73710e.jpg', chipTitle: 'Black Rectangle Sunglasses', chipSub: 'Free product + 15% commission', chipTag: 'Live' }
      ][wayIdx],
      faqs: [
        { q: 'What is Linkable?', a: 'Linkable is where ecommerce brands find creators and run every collaboration in one place. You launch a campaign, creators apply, you choose who to work with, and Linkable handles samples, content, usage rights, tracking and commission payouts.' },
        { q: 'How do I find the right creators?', a: 'Creators in our network apply to your campaign, and AI matching suggests the best fits with the reasons they suit your brand. You can also invite creators directly. You always choose who you work with.' },
        { q: 'What can I offer creators?', a: 'Free product, a fixed fee, commission on sales, or any mix of the three. You set it per campaign.' },
        { q: 'Do I need a Shopify store?', a: 'No. Linkable works without Shopify. Connect it when you want product sync, discount codes and sales attribution.' },
        { q: 'How does the free trial work?', a: 'Every plan is free for the first 30 days, with full access to the platform. Change plan or cancel any time.' },
        { q: 'What counts towards my monthly creator limit?', a: 'Each new creator you start working with in a month counts once. Applications and invitations are unlimited on every plan.' },
        { q: 'What is the 2.5% fee?', a: 'It applies only to sales tracked through creator links and codes. Everything else is covered by your plan.' },
        { q: 'Who owns the content creators make?', a: 'You agree usage rights in each campaign, and they are saved with every piece of content in your library, so you always know where you can use it.' },
        { q: 'Can your team run campaigns for us?', a: 'Yes. Our managed service plans your campaigns, finds the right creators and manages every collaboration from start to finish. Talk to our team to set it up.' }
      ].map((f, i) => ({ ...f, open: i === openFaq, toggle: () => this.setState({ openFaq: i === openFaq ? -1 : i }), rot: i === openFaq ? '45deg' : '0deg', iconBg: i === openFaq ? '#232323' : '#F3F2EE', iconFg: i === openFaq ? '#FFFFFF' : '#232323' })),
      plans: [
        { name: 'Starter', price: '$99', year: '$990', mo: '$83', blurb: 'For brands getting started with creators.', features: ['Work with up to 10 new creators a month', 'Run up to 2 campaigns at once', 'Campaign and creator insights', 'Dedicated support and onboarding'], bg: '#F6F4EF', fg: '#232323', sub: '#666563', line: '#E8E6E1', pillBg: '#232323', pillFg: '#FFFFFF', popular: false, btnClass: 'btn btn-primary btn-arrow' },
        { name: 'Growth', price: '$199', year: '$1,990', mo: '$166', blurb: 'For brands working with creators every month.', features: ['Work with up to 50 new creators a month', 'Run up to 10 campaigns at once', 'Campaign and creator insights', 'Dedicated support and onboarding'], bg: '#232323', fg: '#FFFFFF', sub: '#B5B3AE', line: '#3A3A38', pillBg: '#FFFFFF', pillFg: '#232323', popular: true, btnClass: 'btn btn-ghost btn-arrow' },
        { name: 'Scale', price: '$499', year: '$4,990', mo: '$416', blurb: 'For brands running a full creator program.', features: ['Work with up to 100 new creators a month', 'Run up to 20 campaigns at once', 'Advanced campaign and creator insights', 'Priority support and onboarding'], bg: '#F6F4EF', fg: '#232323', sub: '#666563', line: '#E8E6E1', pillBg: '#232323', pillFg: '#FFFFFF', popular: false, btnClass: 'btn btn-primary btn-arrow' }
      ].map((p) => ({ ...p, shown: yearly ? p.mo : p.price, note: yearly ? 'Billed ' + p.year + ' a year' : 'or ' + p.year + ' a year, save 17%' }))
    };
  }
}
